git:
  depth: 100

sudo: required

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq libxml2-utils libsaxonb-java

language: java

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - xmllint --noout --valid src/standards/standards.xml
  - ant all
  - ant debug

deploy:
  - provider: script
    skip_cleanup: true
    script: "./_scripts/deploy-live-nisp.sh"
    on:
      branch: master
